// <auto-generated />
using System;
using HouseManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HouseManagement.Api.Migrations
{
    [DbContext(typeof(HouseContext))]
    [Migration("20260927195128_AddServiceTaxAndBookingReceiptFields")]
    partial class AddServiceTaxAndBookingReceiptFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HouseManagement.Api.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppliedPromotionCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AppliedPromotionName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("AssignedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedHouseHelpId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("UGX");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("ScheduledEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ScheduledStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ServiceAddressId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRatePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssignedHouseHelpId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("ServiceAddressId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("Status");

                    b.HasIndex("AssignedHouseHelpId", "ScheduledStart", "ScheduledEnd");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.BookingPriceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingPriceLines");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Phone");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.ClientHouseHelpPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("HouseHelpId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HouseHelpId");

                    b.HasIndex("ClientId", "HouseHelpId")
                        .IsUnique();

                    b.ToTable("ClientHouseHelpPreferences");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.HouseHelp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Languages")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalIdLast4")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("ProfileImageSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ProfileImageStorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("ProfileImageUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Unverified");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserId");

                    b.HasIndex("VerificationStatus");

                    b.ToTable("HouseHelps");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.HouseHelpAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("HouseHelpId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("HouseHelpId", "DayOfWeek");

                    b.ToTable("HouseHelpAvailabilities");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.HouseHelpAvailabilityException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("HouseHelpId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("HouseHelpId", "IsActive");

                    b.HasIndex("HouseHelpId", "StartsAt", "EndsAt");

                    b.ToTable("HouseHelpAvailabilityExceptions");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.HouseHelpRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("HouseHelpId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("HouseHelpId");

                    b.ToTable("HouseHelpRatings", t =>
                        {
                            t.HasCheckConstraint("CK_HouseHelpRatings_Score", "[Score] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("HouseManagement.Api.Models.HouseHelpSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HouseHelpId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("HouseHelpId");

                    b.HasIndex("HouseHelpId", "ServiceName")
                        .IsUnique();

                    b.ToTable("HouseHelpSkills");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("int");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MethodType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ProviderCheckoutUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProviderReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("ProviderName", "ProviderReference")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EligibleServiceId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TimesUsed")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EligibleServiceId");

                    b.HasIndex("IsActive");

                    b.HasIndex("StartsAt", "EndsAt");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.PublicHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("PublicHolidays");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTaxable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PricingMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.ServiceAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Line2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.ToTable("ServiceAddresses");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.ServiceFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId", "IsActive");

                    b.ToTable("ServiceFees", t =>
                        {
                            t.HasCheckConstraint("CK_ServiceFees_AdjustmentType", "[AdjustmentType] IN ('Percentage', 'FixedAmount')");

                            t.HasCheckConstraint("CK_ServiceFees_Amount", "([AdjustmentType] = 'FixedAmount' AND [Amount] > 0) OR ([AdjustmentType] = 'Percentage' AND [Amount] > 0 AND [Amount] <= 100)");
                        });
                });

            modelBuilder.Entity("HouseManagement.Api.Models.ServicePriceRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId", "IsActive");

                    b.HasIndex("ServiceId", "UnitName")
                        .IsUnique();

                    b.ToTable("ServicePriceRules");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.ServicePricingVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BillingIncrementMinutes")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MinimumBillableDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("OvertimeThresholdMinutes")
                        .HasColumnType("int");

                    b.Property<decimal?>("OvertimeUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PricingMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TimeBillingUnit")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TimeRoundingPolicy")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal?>("TimeUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .IsUnique()
                        .HasDatabaseName("IX_ServicePricingVersions_ServiceId_OpenPublished")
                        .HasFilter("[Status] = 'Published' AND [EffectiveTo] IS NULL");

                    b.HasIndex("ServiceId", "EffectiveFrom");

                    b.ToTable("ServicePricingVersions", t =>
                        {
                            t.HasCheckConstraint("CK_ServicePricingVersions_BasePrice", "[BasePrice] IS NULL OR [BasePrice] > 0");

                            t.HasCheckConstraint("CK_ServicePricingVersions_BillingIncrement", "[BillingIncrementMinutes] IS NULL OR [BillingIncrementMinutes] > 0");

                            t.HasCheckConstraint("CK_ServicePricingVersions_EffectiveWindow", "[EffectiveTo] IS NULL OR [EffectiveTo] > [EffectiveFrom]");

                            t.HasCheckConstraint("CK_ServicePricingVersions_MinimumDuration", "[MinimumBillableDurationMinutes] IS NULL OR [MinimumBillableDurationMinutes] > 0");

                            t.HasCheckConstraint("CK_ServicePricingVersions_Overtime", "([OvertimeThresholdMinutes] IS NULL AND [OvertimeUnitPrice] IS NULL) OR ([OvertimeThresholdMinutes] IS NOT NULL AND [OvertimeUnitPrice] IS NOT NULL AND [OvertimeThresholdMinutes] >= [MinimumBillableDurationMinutes] AND [OvertimeUnitPrice] > 0)");

                            t.HasCheckConstraint("CK_ServicePricingVersions_PricingMode", "[PricingMode] IN ('Fixed', 'PerUnit', 'TimeBased')");

                            t.HasCheckConstraint("CK_ServicePricingVersions_Status", "[Status] IN ('Draft', 'Published')");

                            t.HasCheckConstraint("CK_ServicePricingVersions_TimeUnitPrice", "[TimeUnitPrice] IS NULL OR [TimeUnitPrice] > 0");
                        });
                });

            modelBuilder.Entity("HouseManagement.Api.Models.ServicePricingVersionUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ServicePricingVersionId")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ServicePricingVersionId", "UnitName")
                        .IsUnique();

                    b.ToTable("ServicePricingVersionUnits", t =>
                        {
                            t.HasCheckConstraint("CK_ServicePricingVersionUnits_UnitPrice", "[UnitPrice] > 0");
                        });
                });

            modelBuilder.Entity("HouseManagement.Api.Models.ServiceSurcharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("AfterHoursEndMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("AfterHoursStartMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LocationMatch")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UrgentLeadTimeMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId", "IsActive");

                    b.ToTable("ServiceSurcharges", t =>
                        {
                            t.HasCheckConstraint("CK_ServiceSurcharges_AdjustmentType", "[AdjustmentType] IN ('Percentage', 'FixedAmount')");

                            t.HasCheckConstraint("CK_ServiceSurcharges_Amount", "([AdjustmentType] = 'FixedAmount' AND [Amount] > 0) OR ([AdjustmentType] = 'Percentage' AND [Amount] > 0 AND [Amount] <= 100)");

                            t.HasCheckConstraint("CK_ServiceSurcharges_TriggerFields", "([TriggerType] = 'AfterHours' AND [AfterHoursStartMinutes] BETWEEN 0 AND 1439 AND [AfterHoursEndMinutes] BETWEEN 0 AND 1439 AND [UrgentLeadTimeMinutes] IS NULL AND [LocationMatch] IS NULL) OR ([TriggerType] = 'Urgent' AND [UrgentLeadTimeMinutes] > 0 AND [AfterHoursStartMinutes] IS NULL AND [AfterHoursEndMinutes] IS NULL AND [LocationMatch] IS NULL) OR ([TriggerType] = 'Location' AND [LocationMatch] IS NOT NULL AND [AfterHoursStartMinutes] IS NULL AND [AfterHoursEndMinutes] IS NULL AND [UrgentLeadTimeMinutes] IS NULL) OR ([TriggerType] IN ('Weekend', 'Holiday') AND [AfterHoursStartMinutes] IS NULL AND [AfterHoursEndMinutes] IS NULL AND [UrgentLeadTimeMinutes] IS NULL AND [LocationMatch] IS NULL)");

                            t.HasCheckConstraint("CK_ServiceSurcharges_TriggerType", "[TriggerType] IN ('Weekend', 'Holiday', 'AfterHours', 'Urgent', 'Location')");
                        });
                });

            modelBuilder.Entity("HouseManagement.Api.Models.ServiceTimePricingPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingIncrementMinutes")
                        .HasColumnType("int");

                    b.Property<string>("BillingUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MinimumBillableDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("OvertimeThresholdMinutes")
                        .HasColumnType("int");

                    b.Property<decimal?>("OvertimeUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoundingPolicy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.ToTable("ServiceTimePricingPolicies", t =>
                        {
                            t.HasCheckConstraint("CK_ServiceTimePricingPolicies_BillingIncrement", "[BillingIncrementMinutes] > 0");

                            t.HasCheckConstraint("CK_ServiceTimePricingPolicies_BillingUnit", "[BillingUnit] IN ('Minute', 'Hour', 'Day')");

                            t.HasCheckConstraint("CK_ServiceTimePricingPolicies_MinimumDuration", "[MinimumBillableDurationMinutes] > 0");

                            t.HasCheckConstraint("CK_ServiceTimePricingPolicies_Overtime", "([OvertimeThresholdMinutes] IS NULL AND [OvertimeUnitPrice] IS NULL) OR ([OvertimeThresholdMinutes] IS NOT NULL AND [OvertimeUnitPrice] IS NOT NULL AND [OvertimeThresholdMinutes] >= [MinimumBillableDurationMinutes] AND [OvertimeUnitPrice] > 0)");

                            t.HasCheckConstraint("CK_ServiceTimePricingPolicies_RoundingPolicy", "[RoundingPolicy] IN ('None', 'Up', 'Down', 'Nearest')");

                            t.HasCheckConstraint("CK_ServiceTimePricingPolicies_UnitPrice", "[UnitPrice] > 0");
                        });
                });

            modelBuilder.Entity("HouseManagement.Api.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.Booking", b =>
                {
                    b.HasOne("HouseManagement.Api.Models.HouseHelp", "AssignedHouseHelp")
                        .WithMany()
                        .HasForeignKey("AssignedHouseHelpId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HouseManagement.Api.Models.Client", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HouseManagement.Api.Models.ServiceAddress", "ServiceAddress")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HouseManagement.Api.Models.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AssignedHouseHelp");

                    b.Navigation("Client");

                    b.Navigation("Service");

                    b.Navigation("ServiceAddress");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.BookingPriceLine", b =>
                {
                    b.HasOne("HouseManagement.Api.Models.Booking", "Booking")
                        .WithMany("PriceLines")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.Client", b =>
                {
                    b.HasOne("HouseManagement.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.ClientHouseHelpPreference", b =>
                {
                    b.HasOne("HouseManagement.Api.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HouseManagement.Api.Models.HouseHelp", "HouseHelp")
                        .WithMany()
                        .HasForeignKey("HouseHelpId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("HouseHelp");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.HouseHelp", b =>
                {
                    b.HasOne("HouseManagement.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.HouseHelpAvailability", b =>
                {
                    b.HasOne("HouseManagement.Api.Models.HouseHelp", "HouseHelp")
                        .WithMany("Availabilities")
                        .HasForeignKey("HouseHelpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HouseHelp");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.HouseHelpAvailabilityException", b =>
                {
                    b.HasOne("HouseManagement.Api.Models.HouseHelp", "HouseHelp")
                        .WithMany("AvailabilityExceptions")
                        .HasForeignKey("HouseHelpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HouseHelp");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.HouseHelpRating", b =>
                {
                    b.HasOne("HouseManagement.Api.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HouseManagement.Api.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HouseManagement.Api.Models.HouseHelp", "HouseHelp")
                        .WithMany()
                        .HasForeignKey("HouseHelpId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Client");

                    b.Navigation("HouseHelp");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.HouseHelpSkill", b =>
                {
                    b.HasOne("HouseManagement.Api.Models.HouseHelp", "HouseHelp")
                        .WithMany("Skills")
                        .HasForeignKey("HouseHelpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HouseHelp");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.Payment", b =>
                {
                    b.HasOne("HouseManagement.Api.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.Promotion", b =>
                {
                    b.HasOne("HouseManagement.Api.Models.Service", "EligibleService")
                        .WithMany()
                        .HasForeignKey("EligibleServiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("EligibleService");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.ServiceFee", b =>
                {
                    b.HasOne("HouseManagement.Api.Models.Service", "Service")
                        .WithMany("Fees")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.ServicePriceRule", b =>
                {
                    b.HasOne("HouseManagement.Api.Models.Service", "Service")
                        .WithMany("PriceRules")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.ServicePricingVersion", b =>
                {
                    b.HasOne("HouseManagement.Api.Models.Service", "Service")
                        .WithMany("PricingVersions")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.ServicePricingVersionUnit", b =>
                {
                    b.HasOne("HouseManagement.Api.Models.ServicePricingVersion", "PricingVersion")
                        .WithMany("Units")
                        .HasForeignKey("ServicePricingVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PricingVersion");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.ServiceSurcharge", b =>
                {
                    b.HasOne("HouseManagement.Api.Models.Service", "Service")
                        .WithMany("Surcharges")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.ServiceTimePricingPolicy", b =>
                {
                    b.HasOne("HouseManagement.Api.Models.Service", "Service")
                        .WithOne("TimePricingPolicy")
                        .HasForeignKey("HouseManagement.Api.Models.ServiceTimePricingPolicy", "ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.Booking", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("PriceLines");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.Client", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.HouseHelp", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("AvailabilityExceptions");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.Service", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Fees");

                    b.Navigation("PriceRules");

                    b.Navigation("PricingVersions");

                    b.Navigation("Surcharges");

                    b.Navigation("TimePricingPolicy");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.ServiceAddress", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HouseManagement.Api.Models.ServicePricingVersion", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
